# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5742d384ac23311b1c84e08eab1b78cb0fdc499d4d532238d13c62767e6aed00ddb8e3f635b301d51238da491f02b7b0b310e865c05402a43fb47b3f4e480878

test:
  secret_key_base: 33794f77f5583367f84e8bf63160e33b9f4f248ab3899e9ad6d9a615253260bc9a403ec7e9d874d52e6c49b4adef6b6af21deb32ed92dd9e740af96bf7fdd7e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
